image: node:16.5.0

before_script:
  - npm install -g pnpm

pages:
  stage: deploy
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: pnpm
    paths:
      - pnpm install
      - pnpm run build
      - cp -a dist/. public/
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
